# Root

[[items]]
name = "button_01"
path = "button_01.py"
type = "button"

[[items]]
name = "button_02"
path = "button_02.py"
type = "button"

[[items]]
name = "apps"
type = "plugin"
plugin = "apps"

[[items]]
name = "obs"
type = "plugin"
plugin = "obs"

[[items]]
name = "pomodoro"
type = "plugin"
plugin = "pomodoro"
